2022-11-21 15:56:42,047 INFO    MainThread:62953 [wandb_setup.py:_flush():68] Configure stats pid to 62953
2022-11-21 15:56:42,047 INFO    MainThread:62953 [wandb_setup.py:_flush():68] Loading settings from /home/yy/.config/wandb/settings
2022-11-21 15:56:42,047 INFO    MainThread:62953 [wandb_setup.py:_flush():68] Loading settings from /home/yy/FGVC/RACNN-pytorch-master/wandb/settings
2022-11-21 15:56:42,047 INFO    MainThread:62953 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-21 15:56:42,048 INFO    MainThread:62953 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'RACNN-pytorch-master/trainer.py', 'program': '/home/yy/FGVC/RACNN-pytorch-master/trainer.py'}
2022-11-21 15:56:42,048 INFO    MainThread:62953 [wandb_init.py:_log_setup():476] Logging user logs to /home/yy/FGVC/RACNN-pytorch-master/wandb/run-20221121_155642-riqww6zw/logs/debug.log
2022-11-21 15:56:42,048 INFO    MainThread:62953 [wandb_init.py:_log_setup():477] Logging internal logs to /home/yy/FGVC/RACNN-pytorch-master/wandb/run-20221121_155642-riqww6zw/logs/debug-internal.log
2022-11-21 15:56:42,048 INFO    MainThread:62953 [wandb_init.py:init():516] calling init triggers
2022-11-21 15:56:42,048 INFO    MainThread:62953 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-21 15:56:42,049 INFO    MainThread:62953 [wandb_init.py:init():569] starting backend
2022-11-21 15:56:42,049 INFO    MainThread:62953 [wandb_init.py:init():573] setting up manager
2022-11-21 15:56:42,054 INFO    MainThread:62953 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-21 15:56:42,056 INFO    MainThread:62953 [wandb_init.py:init():580] backend started and connected
2022-11-21 15:56:42,059 INFO    MainThread:62953 [wandb_init.py:init():658] updated telemetry
2022-11-21 15:56:42,060 INFO    MainThread:62953 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-21 15:56:42,959 INFO    MainThread:62953 [wandb_run.py:_on_init():2000] communicating current version
2022-11-21 15:56:43,599 INFO    MainThread:62953 [wandb_run.py:_on_init():2004] got version response 
2022-11-21 15:56:43,599 INFO    MainThread:62953 [wandb_init.py:init():728] starting run threads in backend
2022-11-21 15:56:44,560 WARNING MainThread:62953 [wandb_init.py:init():1099] interrupted
Traceback (most recent call last):
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 739, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 235, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 255, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 36, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/yy/anaconda3/envs/pytorch_gpu/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
